version: "3.8"
services:
  dev:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspaces/smores:cached
    command: sleep infinity
    depends_on:
      - mqtt

  mqtt:
    image: eclipse-mosquitto:2
    container_name: smores-mqtt
    ports:
      - "1883:1883"
    volumes:
      - ./.mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
